modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (24 is current forge version)
issueTrackerURL="https://minecraft.curseforge.com/projects/the-flying-things/issues/" #optional
[[mods]] #mandatory
modId="flying_things" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Flying Things" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Corail31/trash/master/update_flying_things.json" #optional
displayURL="https://minecraft.curseforge.com/projects/the-flying-things/" #optional
logoFile="logo.png" #optional
credits="Special thanks to the Forge and FML guys." #optional
authors="Corail31" #optional
description='''
The Flying Things introduces enchanted brooms and magic carpets that can be ridden to fly over the world.
'''
[[dependencies.flying_things]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.flying_things]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"